- .gitignore
- Makefile
- inst/examples/discrete_deterministic_sir.R
- inst/examples/discrete_stochastic_seirds.R
- inst/examples/discrete_stochastic_sir.R
- inst/examples/discrete_stochastic_sir_arrays.R
- vignettes/discrete.Rmd
- vignettes/src/discrete.R
This adds a new vignette "discrete" on discrete deterministic and stochastic models, with a strong emphasis on the latter. Explains how binomial, Poisson, and multinomial distributions are used in this context.
Provides a simple example using SIR models and then a more advanced one using a SEIRDS model with imported cases. Still needs some proof-reading but should be useful as it is.
> Doc multinom

- DESCRIPTION
- NEWS.md
- R/generate_c_class.R
- R/generate_c_compiled.R
- R/generate_c_utils.R
- R/generate_r.R
- R/generate_r_class.R
- tests/testthat/run/test-run-delay-continuous.R
- tests/testthat/run/test-run-examples.R
- tests/testthat/run/test-run-general.R
- tests/testthat/test-package.R
This PR allows the `deriv()` method to be used with models that include delays.
Previously this was disabled because we need to be careful about treatment of the history.  However, it's not too hard to do something along the lines of the Right Thing:
* if the model has never been run, there is no history, and so `deriv()` should treat this as if it's still burning the delays in (i.e., use the initial conditions)
* if the model has been run, then running `deriv()` should not affect the history (especially once model resuming is implemented - #141) so we should just use the history stored in the model
In order to support this:
1. the `create` phase initialises the `initial_t` member to `NA` (previously was default-initialised to zero which is not ideal)
2. when using the deriv wrapper from …
> i161: Allow use of deriv in delay models

- DESCRIPTION
- R/odin_parse.R
- R/odin_preprocess.R
- tests/testthat/test-odin-validate.R
- tests/testthat/test-preprocess.R
Found in work on odin.ui - this fixes a couple of corner cases when different types of "empty" string are passed in.
Fixes #171
> GH-171: Better error messages for empty input

- NEWS.md
- R/common.R
- R/generate_c_sexp.R
- tests/testthat/run/test-run-library.R
This had previously been implemented following #116 in the old version, but never merged into master before the rewrite
> mrc-511: Support for 2-arg round

- R/ir_parse.R
- inst/schema.json
- tests/testthat/run/test-run-basic.R
- tests/testthat/test-parse2-general.R
This PR adds support for user variables to take simple arithmetic operations.  The two real cases this is useful are negative numbers:
```
x <- user(-1)
```
and fractions:
```
x <- user(2/3)
```
both of which can either be kept as expressions (which is what we do here) or computed at compile time (which I've chosen not to do)
> mrc-1542: Allow simple operations in user defaults

- DESCRIPTION
- NEWS.md
- R/common.R
- R/generate_c_compiled.R
- R/generate_c_equation.R
- R/generate_r_sexp.R
- R/generate_r_support.R
- R/ir_parse_arrays.R
- R/support.R
- inst/library.c
- tests/testthat/run/test-run-library.R
- tests/testthat/test-parse-inplace.R
- tests/testthat/test-support.R
This PR adds support for `rmhyper`, a multivariate version of `rhyper`.  Takes as arguments a vector `k` of "balls" in each of a number of categories and `n` the number of "balls" to sample without replacement.
~## TODO:~
* ~Document this somewhere (#187)~
* ~Add error if `n` is greater than `sum(k)`~
* ~I've added unreachable code in `generate_c_equation_inplace` that needs to become a check in the parse phase~
Follows the same approach to `rmultinom` in that partial updates are not supported - i.e., the whole lhs is replaced by the sorted version of the rhs, so 
```
x[1,] <- rmhyper(k[1,], n)
```
is not possible.
There is no checking that the lhs and the rhs are the same size and getting this wrong will cause a crash.
> mrc-1621: Support for multivariate hypergeometric samples

- DESCRIPTION
- NEWS.md
- R/generate_c_sexp.R
- tests/testthat/run/test-run-general.R
This PR is an ugly fix to an ugly problem. When working with arrays in initial conditions, the `initial->` added by `ir_substitute` needs to be removed.
I thought that this was related to #193 but it does not appear to be.
Fixes #196
> i196: initial arrays

- DESCRIPTION
- NEWS.md
- R/common.R
- R/generate_c_sexp.R
- tests/testthat/run/test-run-general.R
- vignettes/functions.Rmd
Support for `as.integer`, in order to get integer values for use with array indexing.
Fixes #199
> Add basic as.integer support (#199)

- DESCRIPTION
- NEWS.md
- R/generate_c.R
- R/generate_c_compiled.R
- R/generate_r.R
- R/ir_deserialise.R
- R/ir_parse.R
- R/ir_parse_arrays.R
- R/ir_parse_config.R
- R/ir_serialise.R
- R/misc.R
- R/odin_options.R
- inst/schema.json
- tests/testthat/test-odin-options.R
- tests/testthat/test-package.R
- tests/testthat/test-parse2-config.R
- tests/testthat/test-parse2-general.R
- tests/testthat/test-run-general.R
- tests/testthat/user_fns.R
- tests/testthat/user_fns4.c
This PR expands support for odin's nascent `config(include) <- filename` support:
* custom functions can be passed arrays in their entirety 
* support for non-C targets, with R supported here
See https://github.com/mrc-ide/odin.dust/pull/40 for an example in odin.dust, which is the motivating reason for this PR
> More flexible user-supplied functions

- DESCRIPTION
- R/common.R
- R/ir_parse.R
- R/ir_serialise.R
- inst/schema.json
- tests/testthat/test-ir.R
Clearly this was meant to be here as the enum was there in the schema,
but never got added properly. This is needed for some optimisations in
odin.dust
> mrc-2092: Add "stage" information into the IR

- DESCRIPTION
- R/ir_parse.R
- R/ir_parse_arrays.R
- R/ir_parse_config.R
- R/ir_serialise.R
- inst/schema.json
- tests/testthat/identity.c
- tests/testthat/test-parse2-config.R
This allows some degree of extensibility in the configuration, so that a target (e.g., odin.dust) could allow
```
config(whatever) <- value
```
if the target declares that `whatever` is a valid custom configuration option
> mrc-2117: Allow extendable configuration

- DESCRIPTION
- NEWS.md
- R/ir_parse.R
- tests/testthat/test-parse2-unused.R
This is intended to support compare functions as introduced in dust and supported by odin.dust. In this case we want to mark some equations as allowably unused and suppress a message about an unused variable.
This can be seen fairly easily in the tests, I think.
Note that this does not work with inline odin definitions like:
```
odin({
initial(x) <- 1 
update(x) <- 1
a <- 1 # ignore.unused
})
```
because the comment will be lost. However, it is preserved where the model is loaded from file or defined in text.
> Control notes about unused variables

- DESCRIPTION
- R/common.R
- R/generate_c_sexp.R
- tests/testthat/test-run-library.R
Just passes this through as.numeric to a c cast to double. It's really needed for odin.dust
Merge after #219
> mrc-2251: add support for as.numeric

- DESCRIPTION
- NEWS.md
- R/ir_parse.R
- R/odin_options.R
- R/odin_parse.R
- R/utils.R
- man/odin_options.Rd
- tests/testthat/test-parse2-rewrite.R
- tests/testthat/test-run-basic.R
- tests/testthat/test-util.R
This PR allows substitutions of user values at compile time. So if the model contains
```
a <- user()
```
then we might provide `substitutions = list(a = 10)` and we rewrite this as if the user had written
```
a <- 10
```
This will be most useful with `rewrite_dims` because then we'd be able to follow this through to make arrays compile-time-sized
Fixes #220
> Allow substitution of user values at compile time

- DESCRIPTION
- R/compat.R
- R/ir_parse.R
- tests/testthat/test-run-basic.R
Looks like we should detect
```
output(a[]) <- a[i]
```
too - this is likely to be more error prone than the recommended
```
output(a[]) <- TRUE
```
though
Fixes #228
> Detect vector copy

- DESCRIPTION
- tests/testthat/test-run-examples.R
- vignettes/discrete.Rmd
- vignettes/functions.Rmd
- vignettes/odin.Rmd
Can't test to reproduce.
Merge after 2021-07-14 (10 UTC) and resubmit, to avoid the NOTE about submission being sooner than CRAN wants, despite CRAN wanting it :roll_eyes: 
Fixes #231
> Skip integration tests on CRAN to avoid M1 errors

- DESCRIPTION
- R/opt.R
- tests/testthat/test-parse2-rewrite.R
By checking these, we might be able to drop entire branches, which is nice.
> Allow if/else rewriting

- DESCRIPTION
- R/ir_parse.R
- tests/testthat/test-parse2-general.R
As noticed by @AmyDighe, we confusingly allow named args to calls. This PR throws an error if the user adds one. Turns out that the creates JSON was invalid anyway...
> Disallow named args in calls

- DESCRIPTION
- NEWS.md
- R/odin_preprocess.R
- tests/testthat/test-preprocess.R
This deals with the pathological/adversarial filenames in  https://github.com/mrc-ide/dust/pull/359#issuecomment-1011405080
* We allow parens now - previously they were not recognised as potential filenames and then we tried to parse them as code (if forcing filenames then we generated invalid code). We now create a basename that is reasonably sensible. This is not uncommon as `model (1).R` will be created by re-downloading a file.
* We allow periods within a filename (e.g., `model.txt.R`); the dots were previously not sanitised
* We report better if the file cannot be found (previously the error was `'x' looks like a filename, ...` which does not help the user)
```
> odin::odin("no file here.R")
Loading required namespace: pkgbuild
Error in odin_preprocess_detect(x, type) : 
'no file …
```
> Nicer processing of parentheses in filenames

- DESCRIPTION
- R/generate_js.R
- R/generate_js_equation.R
- R/generate_js_util.R
- R/js.R
- inst/js/dopri.js
- inst/js/support.js
- inst/js/test.js
- inst/js/wrapper.js
- js/package-lock.json
- js/package.json
- tests/testthat/helper-odin.R
- tests/testthat/test-js.R
- tests/testthat/test-run-delay-continuous.R
- tests/testthat/test-run-general.R
This PR merges into #257 not master, and follows from #258, see https://github.com/mrc-ide/odin/compare/mrc-3180...mrc-3214 for a diff that covers just these changes
Quite a lot of small changes to make this work:
* save the initial time
* pass the solution to the rhs and output function
* new equations generated for `delay_index` (on parameter setup, stores an array of indices)
* new equations generated for `delay_continuous` - this is the bulk of the hard bit
~I've manually copied over the change from https://github.com/mrc-ide/dopri-js/pull/15 which is needed to fix DDE solutions~
There's a small breaking change for wodin - rather than passing `dopri.Dopri`, now pass `dopri` as for the delay differential equations we need to use `dopri.DDE` as the solver.
Gratifyingly, effects on the …
> Allow delays from js code

- DESCRIPTION
- R/generate_c.R
- R/generate_js.R
- R/generate_r.R
- R/ir_parse.R
- inst/schema.json
- tests/testthat/test-interface.R
- tests/testthat/test-parse2-general.R
This is a pretty big conceptual change for odin, and hard to really test well in the package as we don't have a good mixed ode/stochastic model to push around (I would rather not have to try and write an SDE solver of course). So here I'm just implementing the metadata collection part as the final changes required in the IR are fairly small and easy enough to think about. We'll then drag this through odin.dust and once both are happy we can merge
Once merged, https://github.com/mrc-ide/odin.dust/pull/103 should be merged fairly shortly as otherwise we break compilation of odin dust models. That in turn requires https://github.com/mrc-ide/mode/pull/24 to be merged first, though nobody depends on that yet
> Start on support for mixed models

- DESCRIPTION
- R/ir_parse.R
- tests/testthat/test-parse2-general.R
Noticed this while setting up tests for https://github.com/mrc-ide/odin.dust/pull/104 - the stochastic functions were excluded from the already-existing function argument checking. So previously this failed nastily:
```
odin::odin({
initial(a) <- 0
update(a) <- a + rnorm(1)
})
```
```
Loading required namespace: pkgbuild
Generating model in c
Re-compiling odinaf787418
─  installing *source* package ‘odinaf787418’ ...
** using staged installation
** libs
gcc -I"/usr/share/R/include" -DNDEBUG   -g -Wall -Wextra -pedantic -Wmaybe-uninitialized -Wno-unused-parameter -Wno-cast-function-type -Wno-missing-field-initializers -O2   -fpic  -std=gnu17 -g -Wall -Wextra -pedantic -Wmaybe-uninitialized -Wno-unused-parameter -Wno-cast-function-type -Wno-missing-field-initializers -O2 …
```
> Validate number of arguments passed to stochastic functions

- DESCRIPTION
- R/common.R
- R/generate_c.R
- R/generate_js.R
- R/generate_r.R
- R/ir_parse.R
- R/ir_serialise.R
- inst/schema.json
- tests/testthat/test-interface.R
- tests/testthat/test-parse2-data.R
This PR provides parse support for the new compare syntax (see https://github.com/mrc-ide/odin.dust/issues/130 and the corresponding PR https://github.com/mrc-ide/odin.dust/issues/131). I doubt we'll ever support this in O.G. odin, but we will eventually in the js version which uses a dust-like target.
Here, we just try and wrangle the input and do as little validation as possible. One nice thing about this approach is that all the bits for checking unused variables etc come along for free.
Note that this is intentionally undocumented; we'll document it properly in odin.dust when supported, and it really will just represent a ghost feature in odin
Alex; just adding you here as a FYI, but any comments very welcome
A reminder of the order of PRs:
* compare/data definition within the odin …
> Proof-of-concept data/compare in odin

- DESCRIPTION
- R/differentiate-support.R
- tests/testthat/helper-differentiate.R
- tests/testthat/test-differentiate-support.R
- tests/testthat/test-run-general.R
Required for differentiating models that contain stochastic distributions. Normally we cope with this in dust by putting distributions into "deterministic mode" which applies the same logic. Here, we do the transformation of a call to a stochastic function (e.g., `rnorm(mu, sd)`) with its expectation (`mu`) symbolically so that we can later differentiate the resulting expressions.
No visible change from any of this to the user, this is just support code to make the eventual autodiff support manageable
> mrc-4324: support for taking expectations of stochastic functions

- DESCRIPTION
- R/differentiate-support.R
- tests/testthat/test-differentiate-support.R
Merge after #296 as it contains those commits (see work plan in mrc-4182).
See https://github.com/mrc-ide/odin/compare/mrc-4324...mrc-4326 for diff of just these changes
This PR computes the log density for some distributions (not many, and not exhaustive unlike #296 as this needs to mirror dust for now and there are a couple of interface issues to nail down later). It is intended to be enough to implement some proof-of-concept models more than anything actually very useful.
Note that there's a difference in how we hit this logic vs the expectations - with the expectations we analyse an expression and then every time we hit a r* function (e.g., `rpois`) we replace the expression with a new one but most expressions pass through unchanged and we only alter things if they match our table of …
> Support for computing log density of distributions

- DESCRIPTION
- R/ir_parse.R
- inst/schema.json
- tests/testthat/test-parse2-differentiate.R
This PR builds on #294 to add control over differentiation of parameters to odin. The syntax for users just replaces
```
scale <- user()
```
with
```
scale <- user(differentiate = TRUE)
```
> Support for differentiation of parameters in DSL

- DESCRIPTION
- R/ir_serialise.R
- README.md
This PR fixes the breaking change coming from R:
> r85227 | maechler | 2023-09-28 09:38:16 +0200 (Thu, 28 Sep 2023) | 1 line
> is.atomic(NULL) now is FALSE
> 
> Please see
> <https://stat.ethz.ch/pipermail/r-devel/2023-September/082892.html> for
> more information and guidance.
> 
> Please correct before 2023-10-14 to safely retain your package on CRAN.
which is producing errors like
```
══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-interface.R:19:3'): n_history is configurable ──────────────────
Error in `ir_serialise_expression(eq$delay$default)`: unhandled expression [odin bug]
Backtrace:
▆
1. └─odin::odin(...) at test-interface.R:19:2
2. └─odin::odin_(...)
3. └─odin::odin_parse_(x, options)
4. └─odin:::ir_parse(x, options, type)
5. …
```
> Fix for CRAN, following change of behaviour of is.atomic(NULL)
